-- ========================================================
-- FitTracks TiDB Update: Ingredients Migration & Data Seed
-- Generated: 2026-09-26 20:54:02
-- Note: Formatted for standard SQL (TiDB Cloud / MySQL compatible)
-- ========================================================

-- 1. Add column if not already added
ALTER TABLE `food_items` ADD COLUMN IF NOT EXISTS `ingredients` TEXT DEFAULT NULL AFTER `recipe_desc`;

-- 2. Populate structured ingredients for staple library dishes
UPDATE `food_items` SET `ingredients` = '[{"name":"Cured beef sirloin tapa","amount":"150","unit":"g","type":"main"},{"name":"Garlic brown rice","amount":"1","unit":"cup","type":"main"},{"name":"Sunny-side up egg","amount":"1","unit":"pc","type":"main"},{"name":"Minced garlic","amount":"3","unit":"cloves","type":"optional"},{"name":"Olive oil","amount":"1","unit":"tsp","type":"optional"},{"name":"Sliced fresh tomatoes","amount":"4","unit":"slices","type":"optional"},{"name":"Spiced cane vinegar dip","amount":"1","unit":"tbsp","type":"optional"}]' WHERE `name` = 'Tapsilog (Beef Tapa, Garlic Brown Rice, Fried Egg)';
UPDATE `food_items` SET `ingredients` = '[{"name":"Marinated boneless milkfish (bangus)","amount":"180","unit":"g","type":"main"},{"name":"Garlic brown rice","amount":"1","unit":"cup","type":"main"},{"name":"Sunny-side up egg","amount":"1","unit":"pc","type":"main"},{"name":"Garlic cloves","amount":"3","unit":"cloves","type":"optional"},{"name":"Fresh calamansi","amount":"2","unit":"pcs","type":"optional"},{"name":"Sliced tomatoes","amount":"4","unit":"slices","type":"optional"}]' WHERE `name` = 'Bangsilog (Grilled Boneless Milkfish, Garlic Rice, Egg)';
UPDATE `food_items` SET `ingredients` = '[{"name":"Homemade skinless chicken longganisa","amount":"150","unit":"g","type":"main"},{"name":"Garlic brown rice","amount":"1","unit":"cup","type":"main"},{"name":"Farm egg","amount":"1","unit":"pc","type":"main"},{"name":"Garlic & crushed black pepper","amount":"1","unit":"tsp","type":"optional"},{"name":"Cucumber slices","amount":"4","unit":"slices","type":"optional"},{"name":"Spiced vinegar dip","amount":"1","unit":"tbsp","type":"optional"}]' WHERE `name` = 'Chicken Longsilog (Skinless Chicken Longganisa, Rice, Egg)';
UPDATE `food_items` SET `ingredients` = '[{"name":"Smoky roasted eggplant (talong)","amount":"150","unit":"g (1 large)","type":"main"},{"name":"Whisked whole eggs","amount":"2","unit":"pcs","type":"main"},{"name":"Garlic brown rice","amount":"3/4","unit":"cup","type":"main"},{"name":"Olive oil","amount":"1","unit":"tsp","type":"optional"},{"name":"Pink Himalayan salt & pepper","amount":"1","unit":"pinch","type":"optional"},{"name":"Fresh tomato slices","amount":"3","unit":"slices","type":"optional"}]' WHERE `name` = 'Tortang Talong (Eggplant Omelet) with Garlic Rice';
UPDATE `food_items` SET `ingredients` = '[{"name":"Crumbled firm organic tofu","amount":"150","unit":"g","type":"main"},{"name":"Garlic brown rice","amount":"3/4","unit":"cup","type":"main"},{"name":"Baby spinach or kangkong","amount":"50","unit":"g","type":"main"},{"name":"Minced garlic","amount":"3","unit":"cloves","type":"optional"},{"name":"Low-sodium tamari / soy sauce","amount":"1","unit":"tbsp","type":"optional"},{"name":"Cane vinegar","amount":"1","unit":"tbsp","type":"optional"},{"name":"Nutritional yeast","amount":"1","unit":"tsp","type":"optional"}]' WHERE `name` = 'Tofu Scramble Adobo Style with Garlic Rice';
UPDATE `food_items` SET `ingredients` = '[{"name":"Rolled oats","amount":"50","unit":"g (1/2 cup)","type":"main"},{"name":"Chocolate whey protein isolate","amount":"30","unit":"g (1 scoop)","type":"main"},{"name":"Pure dark tablea cocoa powder","amount":"1.5","unit":"tbsp","type":"main"},{"name":"Unsweetened almond milk","amount":"1","unit":"cup","type":"main"},{"name":"Chia seeds","amount":"1","unit":"tsp","type":"optional"},{"name":"Creamy roasted almond butter","amount":"1","unit":"tbsp","type":"optional"},{"name":"Stevia / natural sweetener","amount":"to taste","unit":"","type":"optional"}]' WHERE `name` = 'Oatmeal Protein Champorado with Chia & Almond Butter';
UPDATE `food_items` SET `ingredients` = '[{"name":"Whole farm eggs","amount":"3","unit":"pcs","type":"main"},{"name":"Fresh baby spinach","amount":"50","unit":"g","type":"main"},{"name":"Aged cheddar cheese (shredded)","amount":"30","unit":"g","type":"main"},{"name":"Smoked bacon strips","amount":"2","unit":"slices (30 g)","type":"main"},{"name":"Fresh Hass avocado","amount":"1/2","unit":"pc (75 g)","type":"main"},{"name":"Grass-fed butter","amount":"1","unit":"tsp","type":"optional"},{"name":"Cracked black pepper","amount":"1","unit":"pinch","type":"optional"}]' WHERE `name` = 'Keto Bacon, Spinach & Cheddar 3-Egg Omelet with Avocado';
UPDATE `food_items` SET `ingredients` = '[{"name":"Wild smoked salmon fillet slices","amount":"80","unit":"g","type":"main"},{"name":"Artisan sourdough bread","amount":"2","unit":"slices (70 g)","type":"main"},{"name":"Ripe Hass avocado (mashed)","amount":"1/2","unit":"pc (75 g)","type":"main"},{"name":"Soft-boiled eggs","amount":"2","unit":"pcs","type":"main"},{"name":"Fresh lemon juice","amount":"1","unit":"tsp","type":"optional"},{"name":"Fresh dill / microgreens","amount":"1","unit":"tbsp","type":"optional"},{"name":"Red chili flakes","amount":"1","unit":"pinch","type":"optional"}]' WHERE `name` = 'Smoked Salmon Avocado Sourdough Toast with Soft Eggs';
UPDATE `food_items` SET `ingredients` = '[{"name":"Gluten-free rolled oats (blended)","amount":"50","unit":"g (1/2 cup)","type":"main"},{"name":"Ripe banana (mashed)","amount":"1","unit":"medium pc","type":"main"},{"name":"Vanilla whey protein","amount":"25","unit":"g (1 scoop)","type":"main"},{"name":"Egg whites","amount":"2","unit":"pcs (60 ml)","type":"main"},{"name":"Baking powder","amount":"1/2","unit":"tsp","type":"optional"},{"name":"Ground cinnamon","amount":"1/2","unit":"tsp","type":"optional"},{"name":"Sugar-free maple syrup","amount":"1","unit":"tbsp","type":"optional"}]' WHERE `name` = 'Gluten-Free Banana Oat Protein Pancakes';
UPDATE `food_items` SET `ingredients` = '[{"name":"Smoked fish fillet (tinapa)","amount":"150","unit":"g","type":"main"},{"name":"Garlic brown rice","amount":"1","unit":"cup","type":"main"},{"name":"Sunny-side up egg","amount":"1","unit":"pc","type":"main"},{"name":"Sliced fresh tomatoes","amount":"1","unit":"medium pc","type":"optional"},{"name":"Spiced cane vinegar dip","amount":"1","unit":"tbsp","type":"optional"},{"name":"Calamansi","amount":"1","unit":"pc","type":"optional"}]' WHERE `name` = 'Tinapasilog (Smoked Fish, Garlic Rice, Egg)';
UPDATE `food_items` SET `ingredients` = '[{"name":"Skinless chicken breast","amount":"200","unit":"g","type":"main"},{"name":"Garlic brown rice (cooked)","amount":"1","unit":"cup","type":"main"},{"name":"Steamed green cabbage wedges","amount":"100","unit":"g","type":"main"},{"name":"Fresh garlic","amount":"4","unit":"cloves","type":"optional"},{"name":"Low-sodium soy sauce","amount":"2","unit":"tbsp","type":"optional"},{"name":"Cane vinegar","amount":"2","unit":"tbsp","type":"optional"},{"name":"Dried bay leaves","amount":"2","unit":"pcs","type":"optional"},{"name":"Whole black peppercorns","amount":"1","unit":"tsp","type":"optional"}]' WHERE `name` = 'Chicken Breast Adobo with Garlic Brown Rice & Steamed Cabbage';
UPDATE `food_items` SET `ingredients` = '[{"name":"Fresh peeled shrimp","amount":"180","unit":"g","type":"main"},{"name":"Water spinach (kangkong)","amount":"100","unit":"g","type":"main"},{"name":"White radish (labanos) slices","amount":"60","unit":"g","type":"main"},{"name":"Steamed brown rice","amount":"3/4","unit":"cup","type":"main"},{"name":"Ripe native tomatoes","amount":"1","unit":"medium pc","type":"optional"},{"name":"Red onion wedges","amount":"1/2","unit":"pc","type":"optional"},{"name":"Tamarind broth base","amount":"2","unit":"cups","type":"optional"},{"name":"Green finger chili (siling haba)","amount":"1","unit":"pc","type":"optional"}]' WHERE `name` = 'Sinigang na Hipon (Shrimp & Water Spinach in Tamarind Broth)';
UPDATE `food_items` SET `ingredients` = '[{"name":"Whole green mung beans (munggo)","amount":"80","unit":"g (1/2 cup)","type":"main"},{"name":"Firm tofu (crispy seared cubes)","amount":"100","unit":"g","type":"main"},{"name":"Moringa leaves (malunggay)","amount":"1","unit":"cup (30 g)","type":"main"},{"name":"Steamed brown rice","amount":"3/4","unit":"cup","type":"main"},{"name":"Minced garlic & sliced onions","amount":"3","unit":"tbsp","type":"optional"},{"name":"Ripe diced tomatoes","amount":"1","unit":"medium pc","type":"optional"},{"name":"Olive oil","amount":"1","unit":"tsp","type":"optional"}]' WHERE `name` = 'Ginisang Munggo (Mung Bean Stew) with Crispy Tofu & Brown Rice';
UPDATE `food_items` SET `ingredients` = '[{"name":"Chicken breast / leg quarter","amount":"200","unit":"g","type":"main"},{"name":"Steamed brown rice","amount":"1","unit":"cup","type":"main"},{"name":"Pickled green papaya (atchara)","amount":"40","unit":"g","type":"main"},{"name":"Calamansi & lemongrass marinade","amount":"2","unit":"tbsp","type":"optional"},{"name":"Annatto basting oil","amount":"1","unit":"tsp","type":"optional"},{"name":"Sinamak spiced vinegar dip","amount":"1","unit":"tbsp","type":"optional"}]' WHERE `name` = 'Grilled Chicken Inasal with Brown Rice & Pickled Papaya';
UPDATE `food_items` SET `ingredients` = '[{"name":"Atlantic salmon fillet","amount":"180","unit":"g","type":"main"},{"name":"Cooked quinoa","amount":"3/4","unit":"cup","type":"main"},{"name":"Steamed shelled edamame","amount":"1/2","unit":"cup (75 g)","type":"main"},{"name":"Low-sodium teriyaki glaze","amount":"1.5","unit":"tbsp","type":"optional"},{"name":"Toasted sesame seeds","amount":"1","unit":"tsp","type":"optional"},{"name":"Sliced green scallions","amount":"1","unit":"tbsp","type":"optional"}]' WHERE `name` = 'Grilled Salmon Teriyaki Bowl with Quinoa & Edamame';
UPDATE `food_items` SET `ingredients` = '[{"name":"Sitaw / Yard-long beans","amount":"150","unit":"g","type":"main"},{"name":"Firm tofu (pressed & cubed)","amount":"100","unit":"g","type":"main"},{"name":"Cooked quinoa","amount":"1/2","unit":"cup","type":"main"},{"name":"Garlic","amount":"2","unit":"cloves","type":"optional"},{"name":"Low-sodium soy sauce","amount":"1","unit":"tbsp","type":"optional"},{"name":"Cane vinegar","amount":"1","unit":"tbsp","type":"optional"},{"name":"Cooking oil","amount":"1","unit":"tsp","type":"optional"},{"name":"Ground black pepper","amount":"1","unit":"pinch","type":"optional"}]' WHERE `name` = 'Adobong Sitaw & Firm Tofu with Quinoa';
UPDATE `food_items` SET `ingredients` = '[{"name":"Lean pork tenderloin (grilled)","amount":"200","unit":"g","type":"main"},{"name":"Roasted charred eggplant (talong)","amount":"150","unit":"g (1 large)","type":"main"},{"name":"Diced red onion & ripe tomatoes","amount":"3","unit":"tbsp","type":"optional"},{"name":"Calamansi juice & cane vinegar","amount":"1.5","unit":"tbsp","type":"optional"},{"name":"Extra virgin olive oil","amount":"1","unit":"tsp","type":"optional"},{"name":"Sea salt & ground pepper","amount":"1","unit":"pinch","type":"optional"}]' WHERE `name` = 'Keto Grilled Pork Tenderloin with Ensaladang Talong';
UPDATE `food_items` SET `ingredients` = '[{"name":"90/10 extra lean ground beef","amount":"180","unit":"g","type":"main"},{"name":"Diced russet potatoes","amount":"60","unit":"g","type":"main"},{"name":"Sweet green peas","amount":"40","unit":"g","type":"main"},{"name":"Steamed brown rice","amount":"3/4","unit":"cup","type":"main"},{"name":"Diced carrots","amount":"30","unit":"g","type":"optional"},{"name":"Crushed tomatoes & garlic","amount":"1/2","unit":"cup","type":"optional"},{"name":"Olive oil","amount":"1","unit":"tsp","type":"optional"}]' WHERE `name` = 'Lean Beef Picadillo with Diced Potatoes & Peas';
UPDATE `food_items` SET `ingredients` = '[{"name":"Skinless chicken breast chunks","amount":"200","unit":"g","type":"main"},{"name":"Green sayote / chayote wedges","amount":"100","unit":"g","type":"main"},{"name":"Moringa leaves (malunggay)","amount":"1","unit":"cup (30 g)","type":"main"},{"name":"Steamed brown rice","amount":"3/4","unit":"cup","type":"main"},{"name":"Fresh ginger root (julienned)","amount":"20","unit":"g","type":"optional"},{"name":"Sliced red onion & garlic","amount":"2","unit":"tbsp","type":"optional"},{"name":"Nourishing clear broth","amount":"2","unit":"cups","type":"optional"}]' WHERE `name` = 'Chicken Tinola (Ginger Chicken Broth with Sayote & Malunggay)';
UPDATE `food_items` SET `ingredients` = '[{"name":"Grilled round scad (galunggong)","amount":"150","unit":"g","type":"main"},{"name":"Kabocha squash (kalabasa)","amount":"80","unit":"g","type":"main"},{"name":"Eggplant & okra slices","amount":"80","unit":"g","type":"main"},{"name":"String beans (sitaw)","amount":"50","unit":"g","type":"main"},{"name":"Steamed brown rice","amount":"3/4","unit":"cup","type":"main"},{"name":"Sautéed garlic, onions & tomatoes","amount":"3","unit":"tbsp","type":"optional"},{"name":"Low-sodium seasoning broth","amount":"1","unit":"tbsp","type":"optional"}]' WHERE `name` = 'Pinakbet with Grilled Fish & Steamed Rice';
UPDATE `food_items` SET `ingredients` = '[{"name":"Boneless milkfish (bangus)","amount":"220","unit":"g","type":"main"},{"name":"Steamed brown rice","amount":"1","unit":"cup","type":"main"},{"name":"Diced sweet onions & ripe tomatoes","amount":"1","unit":"cup","type":"optional"},{"name":"Ginger slices & fresh calamansi","amount":"2","unit":"tbsp","type":"optional"},{"name":"Banana leaf wrapper for grilling","amount":"1","unit":"sheet","type":"optional"},{"name":"Soy-calamansi dipping sauce","amount":"1","unit":"tbsp","type":"optional"}]' WHERE `name` = 'Inihaw na Bangus (Grilled Milkfish stuffed with Tomatoes & Onions)';
UPDATE `food_items` SET `ingredients` = '[{"name":"Skinless chicken breast skewers","amount":"220","unit":"g (3 skewers)","type":"main"},{"name":"Crisp cucumber slices","amount":"1","unit":"cup (80 g)","type":"main"},{"name":"Cherry tomatoes (halved)","amount":"1/2","unit":"cup (50 g)","type":"main"},{"name":"Calamansi & garlic marinade","amount":"2","unit":"tbsp","type":"optional"},{"name":"Light olive oil vinaigrette","amount":"1","unit":"tbsp","type":"optional"},{"name":"Chopped fresh cilantro / parsley","amount":"1","unit":"tsp","type":"optional"}]' WHERE `name` = 'Chicken Inasal Skewers with Cucumber Tomato Salad';
UPDATE `food_items` SET `ingredients` = '[{"name":"Fresh Atlantic salmon fillet/collar","amount":"180","unit":"g","type":"main"},{"name":"Mustard greens (mustasa) or bok choy","amount":"80","unit":"g","type":"main"},{"name":"White radish & string beans","amount":"60","unit":"g","type":"main"},{"name":"Steamed brown rice","amount":"3/4","unit":"cup","type":"main"},{"name":"Fresh tomatoes & red onion","amount":"1","unit":"medium pc each","type":"optional"},{"name":"Natural tamarind soup base","amount":"2","unit":"cups","type":"optional"},{"name":"Green finger chili","amount":"1","unit":"pc","type":"optional"}]' WHERE `name` = 'Salmon Sinigang (Salmon Head/Fillet in Sour Tamarind Broth)';
UPDATE `food_items` SET `ingredients` = '[{"name":"Air-fried golden tofu cubes","amount":"120","unit":"g","type":"main"},{"name":"Kabocha squash (kalabasa)","amount":"80","unit":"g","type":"main"},{"name":"Bitter melon (ampalaya) & eggplant","amount":"70","unit":"g","type":"main"},{"name":"Steamed brown rice","amount":"3/4","unit":"cup","type":"main"},{"name":"Garlic, shallots & native tomatoes","amount":"3","unit":"tbsp","type":"optional"},{"name":"Low-sodium soy sauce & water","amount":"1/2","unit":"cup","type":"optional"}]' WHERE `name` = 'Vegetable Pinakbet with Air-Fried Tofu & Brown Rice';
UPDATE `food_items` SET `ingredients` = '[{"name":"Dried taro leaves (dahon ng gabi)","amount":"50","unit":"g dry","type":"main"},{"name":"Fresh peeled shrimp","amount":"120","unit":"g","type":"main"},{"name":"Light coconut milk","amount":"3/4","unit":"cup (150 ml)","type":"main"},{"name":"Steamed brown rice","amount":"3/4","unit":"cup","type":"main"},{"name":"Bird''s eye chili (siling labuyo)","amount":"2","unit":"pcs","type":"optional"},{"name":"Ginger strips & minced garlic","amount":"2","unit":"tbsp","type":"optional"},{"name":"Lemongrass knot","amount":"1","unit":"stalk","type":"optional"}]' WHERE `name` = 'Laing (Taro Leaves in Spicy Coconut Milk with Shrimp)';
UPDATE `food_items` SET `ingredients` = '[{"name":"Grass-fed ribeye steak","amount":"250","unit":"g","type":"main"},{"name":"Tender asparagus spears","amount":"100","unit":"g","type":"main"},{"name":"Sliced button mushrooms","amount":"80","unit":"g","type":"main"},{"name":"Grass-fed garlic herb butter","amount":"1.5","unit":"tbsp","type":"optional"},{"name":"Flaked sea salt & fresh rosemary","amount":"1","unit":"pinch","type":"optional"}]' WHERE `name` = 'Keto Grilled Ribeye Steak with Garlic Butter Mushrooms & Asparagus';
UPDATE `food_items` SET `ingredients` = '[{"name":"Shredded chicken breast","amount":"150","unit":"g","type":"main"},{"name":"Brown rice porridge (arroz)","amount":"80","unit":"g dry","type":"main"},{"name":"Hard-boiled egg","amount":"1","unit":"large pc","type":"main"},{"name":"Fresh ginger root (julienned)","amount":"2","unit":"tbsp","type":"optional"},{"name":"Golden toasted garlic chips","amount":"1","unit":"tbsp","type":"optional"},{"name":"Chopped green scallions & calamansi","amount":"2","unit":"tbsp","type":"optional"}]' WHERE `name` = 'Gluten-Free Chicken Arroz Caldo with Hard Boiled Egg';
UPDATE `food_items` SET `ingredients` = '[{"name":"Thinly sliced top round beef sirloin","amount":"180","unit":"g","type":"main"},{"name":"Sweet white onion rings","amount":"100","unit":"g (1 onion)","type":"main"},{"name":"Steamed brown rice","amount":"1","unit":"cup","type":"main"},{"name":"Fresh calamansi juice marinade","amount":"2","unit":"tbsp","type":"optional"},{"name":"Low-sodium soy sauce","amount":"2","unit":"tbsp","type":"optional"},{"name":"Cracked black peppercorns & olive oil","amount":"1","unit":"tsp","type":"optional"}]' WHERE `name` = 'Lean Beef Bistek Tagalog with Onion Rings & Brown Rice';
UPDATE `food_items` SET `ingredients` = '[{"name":"Yellowfin tuna belly steak","amount":"200","unit":"g","type":"main"},{"name":"Steamed brown rice","amount":"1","unit":"cup","type":"main"},{"name":"Cucumber & tomato ensalada","amount":"80","unit":"g","type":"main"},{"name":"Soy-calamansi marinade glaze","amount":"2","unit":"tbsp","type":"optional"},{"name":"Sliced fresh red chilies","amount":"1","unit":"pc","type":"optional"}]' WHERE `name` = 'Grilled Tuna Belly with Steamed Brown Rice & Ensalada';
UPDATE `food_items` SET `ingredients` = '[{"name":"Firm tofu (seared cubes)","amount":"140","unit":"g","type":"main"},{"name":"Native eggplant wedges","amount":"100","unit":"g","type":"main"},{"name":"Long green finger chilies (siling haba)","amount":"50","unit":"g","type":"main"},{"name":"Light coconut cream","amount":"1/2","unit":"cup (120 ml)","type":"main"},{"name":"Steamed brown rice","amount":"3/4","unit":"cup","type":"main"},{"name":"Minced garlic, shallots & ginger","amount":"2","unit":"tbsp","type":"optional"},{"name":"Miso or salted black bean paste","amount":"1","unit":"tsp","type":"optional"}]' WHERE `name` = 'Vegan Bicol Express with Tofu, Eggplant & Coconut Milk';
UPDATE `food_items` SET `ingredients` = '[{"name":"Native saba bananas (steamed)","amount":"2","unit":"pcs (150 g)","type":"main"},{"name":"100% natural roasted peanut butter","amount":"1","unit":"tbsp (16 g)","type":"main"},{"name":"Ceylon cinnamon dust","amount":"1","unit":"pinch","type":"optional"}]' WHERE `name` = 'Boiled Saba Banana with Natural Peanut Butter';
UPDATE `food_items` SET `ingredients` = '[{"name":"Steamed purple / yellow sweet potato (kamote)","amount":"150","unit":"g (1 root)","type":"main"},{"name":"Ground Ceylon cinnamon","amount":"1/2","unit":"tsp","type":"optional"},{"name":"Flaked sea salt","amount":"1","unit":"pinch","type":"optional"}]' WHERE `name` = 'Boiled Kamote (Sweet Potato) with Cinnamon';
UPDATE `food_items` SET `ingredients` = '[{"name":"Whey protein isolate powder","amount":"30","unit":"g (1 scoop)","type":"main"},{"name":"Cold skim milk / almond milk","amount":"300","unit":"ml","type":"main"},{"name":"Ripe banana","amount":"1/2","unit":"pc (50 g)","type":"main"},{"name":"Ice cubes","amount":"4-5","unit":"cubes","type":"optional"},{"name":"Cinnamon dust","amount":"1","unit":"pinch","type":"optional"}]' WHERE `name` = 'Whey Protein Shake with Skim Milk & Half Banana';
UPDATE `food_items` SET `ingredients` = '[{"name":"Free-range large eggs (hard-boiled)","amount":"2","unit":"large pcs","type":"main"},{"name":"Pink Himalayan mineral salt","amount":"1","unit":"pinch","type":"optional"},{"name":"Freshly cracked black pepper","amount":"1","unit":"pinch","type":"optional"}]' WHERE `name` = 'Hard-Boiled Eggs with Pink Himalayan Salt & Black Pepper';
UPDATE `food_items` SET `ingredients` = '[{"name":"Plain thick strained Greek yogurt","amount":"180","unit":"g (1 cup)","type":"main"},{"name":"Fresh blueberries","amount":"75","unit":"g (1/2 cup)","type":"main"},{"name":"Raw crushed almonds","amount":"15","unit":"g (1 tbsp)","type":"main"},{"name":"Pure honey or stevia","amount":"1","unit":"tsp","type":"optional"}]' WHERE `name` = 'Plain Greek Yogurt with Blueberries & Crushed Almonds';
UPDATE `food_items` SET `ingredients` = '[{"name":"Whole green edamame pods (steamed)","amount":"150","unit":"g (1 cup)","type":"main"},{"name":"Flaked sea salt","amount":"1/2","unit":"tsp","type":"optional"},{"name":"Toasted sesame oil drops","amount":"2","unit":"drops","type":"optional"}]' WHERE `name` = 'Steamed Edamame in Pods with Sea Salt';
UPDATE `food_items` SET `ingredients` = '[{"name":"Oven-baked crispy pork rinds (chicharon)","amount":"40","unit":"g bag","type":"main"},{"name":"Spiced garlic cane vinegar","amount":"2","unit":"tbsp","type":"optional"},{"name":"Crushed garlic clove","amount":"1","unit":"clove","type":"optional"}]' WHERE `name` = 'Crispy Baked Pork Rinds (Chicharon) with Vinegar Dip';
UPDATE `food_items` SET `ingredients` = '[{"name":"Crisp Fuji / Gala apple wedges","amount":"150","unit":"g (1 apple)","type":"main"},{"name":"100% natural crunchy almond butter","amount":"16","unit":"g (1 tbsp)","type":"main"},{"name":"Cinnamon powder","amount":"1","unit":"pinch","type":"optional"}]' WHERE `name` = 'Apple Slices with Crunchy Almond Butter';
UPDATE `food_items` SET `ingredients` = '[{"name":"Chunk light tuna in water (drained)","amount":"120","unit":"g (1 can)","type":"main"},{"name":"Whole grain wheat crackers","amount":"4","unit":"crackers (30 g)","type":"main"},{"name":"Light mayonnaise or Greek yogurt","amount":"1","unit":"tbsp","type":"optional"},{"name":"Diced crisp celery & red onion","amount":"2","unit":"tbsp","type":"optional"},{"name":"Lemon juice & cracked pepper","amount":"1","unit":"tsp","type":"optional"}]' WHERE `name` = 'Tuna Salad on Whole Wheat Crackers';
UPDATE `food_items` SET `ingredients` = '[{"name":"Low-fat curd cottage cheese","amount":"200","unit":"g (1 cup)","type":"main"},{"name":"Fresh sweet pineapple chunks","amount":"80","unit":"g (1/2 cup)","type":"main"},{"name":"Fresh mint leaf sprig","amount":"1","unit":"pc","type":"optional"}]' WHERE `name` = 'Cottage Cheese with Fresh Pineapple Chunks';
